## 1. 자연어
자연어는 인간이 일상적으로 의사소통에 사용하는 언어로, 말과 글을 통해 표현되는 언어를 말합니다. 자연어는 문법, 어휘, 맥락, 뉘앙스 등 복잡한 요소들로 이루어져 있어 규칙적인 구조와 함께 다양한 변형이 가능합니다. 컴퓨터 과학에서는 이러한 자연어를 이해하고 처리하기 위해 자연어 처리(NLP, Natural Language Processing) 기술이 사용되며, 이를 통해 텍스트 분석, 번역, 음성 인식, 챗봇과 같은 다양한 응용이 가능합니다. 자연어는 인간의 사고와 문화적 배경을 반영하므로, 이를 다루는 기술은 인문학적 이해와 기술적 접근이 결합되어야 합니다.

## 2. 자연어 처리
자연어 처리는(Natural Language Processing, NLP) 컴퓨터가 인간의 언어를 이해하고 처리하며 생성할 수 있도록 돕는 인공지능 기술 분야입니다. 이를 통해 텍스트나 음성 데이터를 분석하고, 번역, 요약, 감정 분석, 질의응답, 음성인식 등 다양한 작업을 수행할 수 있습니다. 자연어 처리는 언어학, 컴퓨터 과학, 인공지능의 융합으로 이루어지며, 형태소 분석, 구문 분석, 의미 분석 등 여러 단계를 포함합니다. 최근에는 딥러닝 기술과 대규모 언어 모델의 발전으로 자연어 처리 성능이 크게 향상되어 챗봇, 검색 엔진, 추천 시스템과 같은 실생활 응용에서 널리 사용되고 있습니다.

## 3. 토큰화
토큰화(Tokenization)는 텍스트 데이터를 분석하거나 처리하기 위해 문장을 의미 있는 단위로 나누는 과정입니다. 이 단위는 단어, 어절, 형태소, 또는 문자 단위일 수 있으며, 자연어 처리(NLP)의 기초 단계로 매우 중요한 역할을 합니다. 예를 들어, 영어에서는 공백이나 구두점을 기준으로 단어를 나누는 것이 일반적이지만, 한국어나 일본어처럼 공백이 명확하지 않은 언어에서는 형태소 분석기를 사용하여 어절이나 형태소 단위로 나누는 작업이 필요합니다.

### 문장 토큰화

문장 토큰화는 텍스트를 문장 단위로 나누는 과정입니다. 일반적으로 마침표(.), 물음표(?), 느낌표(!)와 같은 문장 부호를 기준으로 문장을 구분합니다. 예를 들어, "안녕하세요. 오늘 날씨가 좋네요!"라는 문장은 "안녕하세요."와 "오늘 날씨가 좋네요!"로 나눌 수 있습니다.

하지만 약어(예: "Dr.", "Mr.")나 숫자(예: "3.14")처럼 마침표를 포함하지만 문장 경계가 아닌 경우를 처리해야 하므로 복잡한 규칙이나 모델이 필요합니다. 문장 토큰화는 문서 요약, 감정 분석, 번역 등의 작업에서 중요한 역할을 합니다. (한국어에서의 문장 토크나이저로 'KSS'를 추천)

[KSS 링크](https://github.com/hyunwoongko/kss)

In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
import numpy as np

In [4]:
# 전처리할 텍스트를 정합니다.
text = '커피 한잔 어때'

tokenizer = Tokenizer()     # 토큰화 함수 지정
tokenizer.fit_on_texts([text])      # 단어를 인덱싱 시켜줌

In [6]:
sequences = tokenizer.texts_to_sequences([text])
sequences

[[1, 2, 3]]

In [7]:
# 단어 인덱스 확인
word_index = tokenizer.word_index
print("단어 인덱스: ", word_index)

단어 인덱스:  {'커피': 1, '한잔': 2, '어때': 3}


- Tokenizer는 기본적으로 띄어쓰기(whitespace)를 기준으로 단어를 나눕니다.
- 그리고 단어 안에 있는 일부 특수문자나 구두점(, . ! ? 등)은 제거합니다.
- 모두 소문자(lowercase)로 변환합니다 (영어 기준).
- 그래서 Tokenizer를 그냥 쓰면 공백 단위 토큰화 + 단순한 전처리만 적용됩니다.

In [8]:
# 단어 빈도수 세기

# 전처리하려는 세 개의 문장을 정합니다.
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.',
       ]

In [9]:
# 토큰화 함수를 이용해 전처리 하는 과정입니다.
tokenizer = Tokenizer()            # 토큰화 함수 지정
tokenizer.fit_on_texts(docs)       # 토큰화 함수에 문장 적용

In [10]:
# 단어의 빈도수를 계산한 결과를 각 옵션에 맞추어 출력합니다.
print("단어 카운트: ", tokenizer.word_counts)

# 단어 빈도수는 그 문단에서 중요도를 나타내기때문에 고려해야함

단어 카운트:  OrderedDict({'먼저': 1, '텍스트의': 2, '각': 1, '단어를': 1, '나누어': 1, '토큰화합니다': 1, '단어로': 1, '토큰화해야': 1, '딥러닝에서': 2, '인식됩니다': 1, '토큰화한': 1, '결과는': 1, '사용할': 1, '수': 1, '있습니다': 1})


In [11]:
# 출력되는 순서는 랜덤입니다.
print("문장 카운트: ", tokenizer.document_count)
print("각 단어가 몇 개의 문장에 포함되어 있는가: ", tokenizer.word_docs)
print("각 단어에 매겨진 인덱스 값: ",  tokenizer.word_index)

문장 카운트:  3
각 단어가 몇 개의 문장에 포함되어 있는가:  defaultdict(<class 'int'>, {'텍스트의': 2, '먼저': 1, '각': 1, '단어를': 1, '토큰화합니다': 1, '나누어': 1, '토큰화해야': 1, '딥러닝에서': 2, '인식됩니다': 1, '단어로': 1, '있습니다': 1, '수': 1, '토큰화한': 1, '사용할': 1, '결과는': 1})
각 단어에 매겨진 인덱스 값:  {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


In [15]:
# 전처리할 텍스트를 정합니다.
texts = ['커피 한잔 어때', '오늘 날씨 참 좋네', '옷이 어울려요']

# Tokenizer 객체 생성 및 fit_on_texts로 단어 인덱스 학습
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

# texts_to_sequences로 텍스트를 시퀀스로 변환
sequences = tokenizer.texts_to_sequences(texts)
sequences

# 단어 인덱스 확인
word_index = tokenizer.word_index
print("\n단어 인덱스:\n", word_index)

# 자연어 처리의 규칙
# 문장의 길이를 어느정도 맞춰서 넣기


단어 인덱스:
 {'커피': 1, '한잔': 2, '어때': 3, '오늘': 4, '날씨': 5, '참': 6, '좋네': 7, '옷이': 8, '어울려요': 9}


In [16]:
print("\n시퀀스:\n", sequences)
padded_sequences = pad_sequences(sequences, 4)
print("\n패딩된 시퀀스:\n", padded_sequences)
# 자연어처리에서는 0번을 패딩으로 생각하기때문에 단어 인덱스가 1번부터 시작한다.


시퀀스:
 [[1, 2, 3], [4, 5, 6, 7], [8, 9]]

패딩된 시퀀스:
 [[0 1 2 3]
 [4 5 6 7]
 [0 0 8 9]]


In [17]:
model = Sequential()
# 임배딩 -> 다 원핫 인코딩 등 맞춰준다.
# input_dim에 1을 더하는 것은 인덱스 0을 패딩 값으로 사용하기 위함.
# Keras의 Tokenizer는 단어 인덱스를 1부터 시작하기 때문에, 인덱스 0은 패딩 값으로 예약
# output_dim은 단어가 임베딩될 벡터의 길이
model.add(Embedding(input_dim=len(word_index) + 1, output_dim=5))

# 임베딩 결과 확인
embedding_output = model.predict(padded_sequences)
print("\n임베딩 결과:\n", embedding_output)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step

임베딩 결과:
 [[[ 4.1196752e-02  4.6309505e-02  1.9549731e-02 -9.0062506e-03
   -2.7448345e-02]
  [ 8.7644085e-03  4.8514869e-02  4.5654844e-02 -4.5635760e-02
    1.4778543e-02]
  [ 4.3905500e-02  3.9469823e-03  4.1157827e-03 -3.3752225e-02
    6.5724961e-03]
  [ 3.5548154e-02  2.3774493e-02 -4.0423386e-03 -2.7179612e-02
    3.2103729e-02]]

 [[-9.8926052e-03  4.4136528e-02  4.9469899e-02  4.5681987e-02
    4.4318203e-02]
  [ 4.7351371e-02 -5.8514476e-03 -3.6163498e-02 -8.9179389e-03
   -3.1272639e-02]
  [ 4.4655625e-02  4.3686900e-02 -4.2319000e-02  3.8088847e-02
   -1.7012488e-02]
  [-3.2281712e-02 -2.5527323e-02  3.3170357e-03  1.3251793e-02
    3.5981964e-02]]

 [[ 4.1196752e-02  4.6309505e-02  1.9549731e-02 -9.0062506e-03
   -2.7448345e-02]
  [ 4.1196752e-02  4.6309505e-02  1.9549731e-02 -9.0062506e-03
   -2.7448345e-02]
  [-3.0615365e-02 -4.5940161e-02  4.8717584e-02  3.1159285e-02
   -2.6087165e-03]
  [ 4.9671661e-02 -2.8872862e-03 -3.7124109e-